CREATE INDEX PAYMENT_API_APP.INDEX_REQUEST_PAYMENT_ID
    ON PAYMENT_API_APP.REQUEST (PAYMENT_ID) online;
CREATE INDEX PAYMENT_API_APP.INDEX_CARD_DATA_PAYMENT_ID
    ON PAYMENT_API_APP.CARD_DATA (PAYMENT_ID) online;
CREATE INDEX PAYMENT_API_APP.INDEX_NSPK_DATA_REQUEST_ID
    ON PAYMENT_API_APP.NSPK_DATA (REQUEST_ID) online;
CREATE INDEX PAYMENT_API_APP.INDEX_NSPK_DATA_PAYMENT_ID
    ON PAYMENT_API_APP.NSPK_DATA (PAYMENT_ID) online;