version: '3.8'

services:
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-data:/var/lib/grafana
    depends_on:
      - prometheus

  ignite:
    image: apacheignite/ignite:latest
    container_name: ignite
    ports:
      - "10800:10800"  # Port for client connections
      - "47100:47100"  # Port for communication SPI
      - "47500:47500"  # Port for discovery SPI
      - "49112:49112"  # Port for JMX metrics
    volumes:
      - ignite-data:/data

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'

volumes:
  grafana-data:
  ignite-data:
