server:
  port: 8080
  shutdown: graceful
spring:
  application:
    name: payment-api-demo
  datasource:
    url: jdbc:postgresql://77.232.142.33:5432/payment_api_app
    username: payment_api_app
    password: AdminPass
    driver-class-name: org.postgresql.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      idle-timeout: 30000
      max-lifetime: 1800000
      keepalive-time: 30000
      minimum-idle: 5
      maximum-pool-size: 20
      connection-timeout: 10000
      connection-test-query: select 1
      schema: payment_api_app
      dataSourceProperties:
        socketTimeout: 30
        tcpKeepAlive: true
  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        use_sql_comments: true
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
      hibernate.default_schema: payment_api_app
  transaction:
    default-timeout: 60
  cloud:
    discovery:
      enabled: false
  lifecycle:
    timeout-per-shutdown-phase: 60s
  liquibase:
    enabled: false

app:
  ignite:
    addresses: 77.232.142.33:10800
    expire-policy-duration: 60
  executor:
    core-size: 5
    max-size: 10
  retry:
    retry-count: 10
    delay: 1000

management:
  server:
    port: 8090
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    db:
      enabled: false
    diskspace:
      enabled: false
    rabbit:
      enabled: false

logging:
  level:
    org.springframework.jdbc.core.JdbcTemplate: DEBUG
